<?php

/**
 * PluginDmTalkRoomTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmTalkRoomTable extends myDoctrineTable
{
  public function getRoomsSinceHours($hours)
  {
  	$seconds = 36000 * $hours;
    return $this->createQuery('s')
    ->where('s.created_at > now() - '.$seconds)
    ->execute();
  }
}




