<?php

/**
 * PluginDmTalkRoomTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmTalkRoomTable extends myDoctrineTable
{
  public function getRoomsSince24H()
  {
    return $this->createQuery('s')
    ->where('s.created_at > now() - 86400')
    ->execute();
  }
}




